# Generated by Django 2.1.4 on 2019-01-16 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('short_name', models.CharField(blank=True, default='', max_length=15)),
                ('telescopes', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('altitude', models.FloatField(default=0)),
                ('url', models.CharField(blank=True, default='', max_length=150)),
                ('weatherurl', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.TextField(blank=True, default='')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=models.SET(users.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Photometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=50)),
                ('wavelength', models.FloatField(default=0)),
                ('measurement', models.FloatField()),
                ('error', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('upper_limit', models.BooleanField(default=False)),
                ('lower_limit', models.BooleanField(default=False)),
                ('source', models.TextField(default='')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=models.SET(users.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Star')),
            ],
            options={
                'ordering': ['wavelength', 'band'],
            },
        ),
        migrations.CreateModel(
            name='SpecFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hjd', models.FloatField(default=0)),
                ('instrument', models.CharField(default='', max_length=200)),
                ('filetype', models.CharField(default='', max_length=200)),
                ('specfile', models.FileField(upload_to='spectra/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=models.SET(users.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hjd', models.FloatField(default=0)),
                ('objectname', models.CharField(default='', max_length=50)),
                ('ra', models.FloatField(default=0)),
                ('dec', models.FloatField(default=0)),
                ('alt', models.FloatField(default=0)),
                ('az', models.FloatField(default=0)),
                ('airmass', models.FloatField(default=0)),
                ('exptime', models.FloatField(default=0)),
                ('barycor', models.FloatField(default=0)),
                ('telescope', models.CharField(default='', max_length=200)),
                ('instrument', models.CharField(default='', max_length=200)),
                ('observer', models.CharField(default='', max_length=50)),
                ('moon_illumination', models.FloatField(default=0)),
                ('moon_separation', models.FloatField(default=0)),
                ('wind_speed', models.FloatField(default=0)),
                ('wind_direction', models.FloatField(default=0)),
                ('seeing', models.FloatField(default=0)),
                ('fluxcal', models.BooleanField(default=False)),
                ('flux_units', models.CharField(default='ergs/cm/cm/s/A', max_length=50)),
                ('valid', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=models.SET(users.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('observatory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.Observatory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Project')),
                ('star', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stars.Star')),
            ],
        ),
        migrations.AddField(
            model_name='specfile',
            name='spectrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.Spectrum'),
        ),
    ]
