# Generated by Django 2.1.4 on 2019-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specfile',
            name='dec',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='specfile',
            name='ra',
            field=models.FloatField(default=0),
        ),
    ]
