# Generated by Django 2.1.4 on 2019-02-09 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stars', '0001_initial'),
        ('observations', '0002_auto_20190204_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightCurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hjd', models.FloatField(default=0)),
                ('hjd_start', models.FloatField(default=0)),
                ('hjd_end', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('objectname', models.CharField(default='', max_length=50)),
                ('ra', models.FloatField(default=-1)),
                ('dec', models.FloatField(default=-1)),
                ('alt', models.FloatField(default=-1)),
                ('az', models.FloatField(default=-1)),
                ('airmass', models.FloatField(default=-1)),
                ('exptime', models.FloatField(default=-1)),
                ('cadence', models.FloatField(default=-1)),
                ('passband', models.CharField(default='', max_length=100)),
                ('telescope', models.CharField(default='', max_length=200)),
                ('instrument', models.CharField(default='', max_length=200)),
                ('observer', models.CharField(default='', max_length=50)),
                ('filetype', models.CharField(default='UK', max_length=200)),
                ('moon_illumination', models.FloatField(default=-1)),
                ('moon_separation', models.FloatField(default=-1)),
                ('wind_speed', models.FloatField(default=-1)),
                ('wind_direction', models.FloatField(default=-1)),
                ('seeing', models.FloatField(default=-1)),
                ('valid', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('lcfile', models.FileField(upload_to='lightcurves/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=models.SET(users.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='observatory',
            name='space_craft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='resolution',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='specfile',
            name='dec',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='specfile',
            name='hjd',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='specfile',
            name='ra',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='airmass',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='alt',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='az',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='barycor',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='dec',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='exptime',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='moon_illumination',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='moon_separation',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='ra',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='seeing',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='wind_direction',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='wind_speed',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='observatory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.Observatory'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Project'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stars.Star'),
        ),
    ]
