# Generated by Django 2.1.4 on 2019-03-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_auto_20190209_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='snr',
            field=models.FloatField(default=-1),
        ),
    ]
