# Generated by Django 2.1.4 on 2019-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_spectrum_snr'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='maxwave',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='minwave',
            field=models.FloatField(default=-1),
        ),
    ]
