# Generated by Django 3.1.5 on 2021-01-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20190304_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='specfile',
            name='filename',
            field=models.CharField(default='', max_length=200),
        ),
    ]
