# Generated by Django 3.2.5 on 2021-12-07 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import observations.auxil.fileio
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stars', '0001_initial'),
        ('observations', '0006_specfile_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specfile',
            name='filename',
        ),
        migrations.AlterField(
            model_name='specfile',
            name='specfile',
            field=models.FileField(upload_to=observations.auxil.fileio.get_specfile_path),
        ),
        migrations.CreateModel(
            name='RawSpecFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hjd', models.FloatField(default=-1)),
                ('instrument', models.CharField(default='', max_length=200)),
                ('filetype', models.CharField(default='', max_length=200)),
                ('exptime', models.FloatField(default=-1)),
                ('rawfile', models.FileField(upload_to=observations.auxil.fileio.get_rawfile_path)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=models.SET(users.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.project')),
                ('specfile', models.ManyToManyField(blank=True, to='observations.SpecFile')),
            ],
        ),
    ]
