# Generated by Django 4.0.1 on 2022-01-11 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stars', '0002_alter_tag_name'),
        ('observations', '0007_auto_20211207_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='barycor_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='normalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='barycor',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(default='', max_length=50)),
                ('objectname', models.CharField(default='', max_length=50)),
                ('ra', models.FloatField(default=-1)),
                ('dec', models.FloatField(default=-1)),
                ('create_new_star', models.BooleanField(default=True)),
                ('classification', models.CharField(default='', max_length=50)),
                ('classification_type', models.CharField(default='PH', max_length=2)),
                ('observatory_name', models.CharField(default='', max_length=100)),
                ('observatory_latitude', models.FloatField(default=-1)),
                ('observatory_longitude', models.FloatField(default=-1)),
                ('observatory_altitude', models.FloatField(default=-1)),
                ('observatory_is_spacecraft', models.BooleanField(default=False)),
                ('telescope', models.CharField(default='', max_length=200)),
                ('instrument', models.CharField(default='', max_length=200)),
                ('hjd', models.FloatField(default=-1)),
                ('exptime', models.FloatField(default=-1)),
                ('resolution', models.FloatField(default=-1)),
                ('snr', models.FloatField(default=-1)),
                ('observer', models.CharField(default='', max_length=50)),
                ('wind_speed', models.FloatField(default=-1)),
                ('wind_direction', models.FloatField(default=-1)),
                ('seeing', models.FloatField(default=-1)),
                ('airmass', models.FloatField(default=-1)),
                ('normalized', models.BooleanField(default=False)),
                ('barycor_bool', models.BooleanField(default=True)),
                ('fluxcal', models.BooleanField(default=False)),
                ('flux_units', models.CharField(default='', max_length=50)),
                ('note', models.TextField(default='')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=models.SET(users.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('observatory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.observatory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.project')),
                ('spectrum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.spectrum')),
            ],
        ),
    ]
