# Generated by Django 4.0.1 on 2022-04-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_alter_tag_options'),
        ('observations', '0008_spectrum_barycor_bool_spectrum_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawspecfile',
            name='obs_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rawspecfile',
            name='star',
            field=models.ManyToManyField(blank=True, to='stars.Star'),
        ),
        migrations.AddField(
            model_name='specfile',
            name='obs_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
