# Generated by Django 4.0.1 on 2022-07-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_rawspecfile_obs_date_rawspecfile_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='decomposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
