# Generated by Django 4.1.2 on 2023-01-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_spectrum_decomposed_spectrum_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='specfile',
            name='exptime',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='specfile',
            name='resolution',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='specfile',
            name='snr',
            field=models.FloatField(default=-1),
        ),
    ]
