# Generated by Django 6.0.7 on 2026-07-22 07:48

from django.db import migrations, models

import observations.auxil.fileio
import observations.models.observatory


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0013_list_query_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallightcurve',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalrawspecfile',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalspecfile',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rawspecfile',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='specfile',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalobservatory',
            name='weatherurl',
            field=models.CharField(
                blank=True,
                default='',
                max_length=150,
                validators=[observations.models.observatory.validate_weatherurl_template],
            ),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='lcfile',
            field=models.FileField(upload_to=observations.auxil.fileio.get_lightcurve_path),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='weatherurl',
            field=models.CharField(
                blank=True,
                default='',
                max_length=150,
                validators=[observations.models.observatory.validate_weatherurl_template],
            ),
        ),
    ]
