# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_auto_20170223_1318'),
        ('spectra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=50)),
                ('measurement', models.FloatField()),
                ('error', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('source', models.TextField(default=b'')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Star')),
            ],
        ),
    ]
