# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0002_photometry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photometry',
            options={'ordering': ['wavelength', 'band']},
        ),
        migrations.AddField(
            model_name='photometry',
            name='wavelength',
            field=models.FloatField(default=0),
        ),
    ]
