# Generated by Django 4.1.2 on 2023-01-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='slug',
            field=models.SlugField(default='', max_length=10),
        ),
    ]
