# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='average',
            field=models.BooleanField(default=False),
        ),
    ]
