# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_parameter_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedParameter',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analysis.Parameter')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='derived_parameters', to='analysis.Parameter')),
            ],
            bases=('analysis.parameter',),
        ),
    ]
