# Generated by Django 4.1.2 on 2023-07-24 09:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stars', '0004_remove_identifier_added_on_and_more'),
        ('analysis', '0002_alter_method_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='method',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='method',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='method',
            name='last_modified',
        ),
        migrations.CreateModel(
            name='HistoricalMethod',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('slug', models.SlugField(default='', max_length=10)),
                ('color', models.CharField(default='#8B0000', max_length=7)),
                ('data_type', models.CharField(choices=[('gen', 'Generic'), ('sed', 'SED hdf5')], default='gen', max_length=7)),
                ('derived_parameters', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stars.project')),
            ],
            options={
                'verbose_name': 'historical method',
                'verbose_name_plural': 'historical methods',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDataSource',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('note', models.TextField(default='')),
                ('reference', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stars.project')),
            ],
            options={
                'verbose_name': 'historical data source',
                'verbose_name_plural': 'historical data sources',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDataSet',
            fields=[
                ('datasource_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='analysis.datasource')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('note', models.TextField(default='')),
                ('reference', models.TextField(default='')),
                ('datafile', models.TextField(max_length=100)),
                ('valid', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='analysis.method')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stars.project')),
                ('star', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stars.star')),
            ],
            options={
                'verbose_name': 'historical data set',
                'verbose_name_plural': 'historical data sets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
