# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_derivedparameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='derivedparameter',
            old_name='dependencies',
            new_name='source_parameters',
        ),
    ]
