# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20170306_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='cname',
            field=models.CharField(default=b'', max_length=52),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
