# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20170308_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='derived_parameters',
            field=models.TextField(default=''),
        ),
    ]
