# Generated by Django 6.0.6 on 2026-06-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_model_meta_sync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalanalysis',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical analysis', 'verbose_name_plural': 'historical analysiss'},
        ),
    ]
