# Generated by Django 6.0.6 on 2026-07-14 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_analysis_observation_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalparameterconsensuspolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical parameter consensus policy', 'verbose_name_plural': 'historical parameter consensus policys'},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='category',
            field=models.CharField(choices=[('rv_curve', 'RV curve'), ('sed_fit', 'SED fit'), ('lightcurve_fit', 'Light curve fit'), ('spectral_fit', 'Spectral fit'), ('cross_corr', 'Cross correlation'), ('generic', 'Generic'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalanalysis',
            name='category',
            field=models.CharField(choices=[('rv_curve', 'RV curve'), ('sed_fit', 'SED fit'), ('lightcurve_fit', 'Light curve fit'), ('spectral_fit', 'Spectral fit'), ('cross_corr', 'Cross correlation'), ('generic', 'Generic'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.CreateModel(
            name='AnalysisFit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_id', models.CharField(max_length=128)),
                ('label', models.CharField(default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=255)),
                ('is_best_fit', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fits', to='analysis.analysis')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_fits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_analysisfit',
                'ordering': ['-is_best_fit', 'label', 'fit_id'],
                'constraints': [models.UniqueConstraint(fields=('analysis', 'fit_id'), name='analysis_fit_unique_per_container')],
            },
        ),
    ]
