# Generated by Django 6.0.6 on 2026-07-14 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_analysis_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparameterconsensuspolicy',
            name='fallback_rule',
            field=models.CharField(blank=True, choices=[('weighted_average', 'Weighted average'), ('preferred_source', 'Preferred parameter source'), ('preferred_analysis_category', 'Preferred analysis category'), ('preferred_best_fit', 'Preferred container best fit'), ('source_priority', 'Source priority list'), ('latest', 'Latest measurement')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalparameterconsensuspolicy',
            name='rule',
            field=models.CharField(choices=[('weighted_average', 'Weighted average'), ('preferred_source', 'Preferred parameter source'), ('preferred_analysis_category', 'Preferred analysis category'), ('preferred_best_fit', 'Preferred container best fit'), ('source_priority', 'Source priority list'), ('latest', 'Latest measurement')], max_length=40),
        ),
        migrations.AlterField(
            model_name='parameterconsensuspolicy',
            name='fallback_rule',
            field=models.CharField(blank=True, choices=[('weighted_average', 'Weighted average'), ('preferred_source', 'Preferred parameter source'), ('preferred_analysis_category', 'Preferred analysis category'), ('preferred_best_fit', 'Preferred container best fit'), ('source_priority', 'Source priority list'), ('latest', 'Latest measurement')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='parameterconsensuspolicy',
            name='rule',
            field=models.CharField(choices=[('weighted_average', 'Weighted average'), ('preferred_source', 'Preferred parameter source'), ('preferred_analysis_category', 'Preferred analysis category'), ('preferred_best_fit', 'Preferred container best fit'), ('source_priority', 'Source priority list'), ('latest', 'Latest measurement')], max_length=40),
        ),
        migrations.CreateModel(
            name='AnalysisRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_analysis_id', models.IntegerField(unique=True)),
                ('fit_id', models.CharField(blank=True, default='', max_length=128)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_redirects', to='analysis.analysis')),
            ],
            options={
                'db_table': 'analysis_analysisredirect',
            },
        ),
    ]
