# Generated by Django 6.0.7 on 2026-07-22 07:48

from django.db import migrations, models

import analysis.models.analysis_model


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_fix_analysis_id_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalanalysis',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='datafile',
            field=models.FileField(upload_to=analysis.models.analysis_model._analysis_upload_to),
        ),
    ]
