# Generated by Django 2.1.4 on 2019-01-16 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('href', models.CharField(blank=True, max_length=400)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('description', models.TextField(default='')),
                ('logo', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('is_public', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=models.SET(users.models.get_sentinel_user), related_name='added_projects', to=settings.AUTH_USER_MODEL)),
                ('project_managers', models.ManyToManyField(blank=True, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('readonly_users', models.ManyToManyField(blank=True, related_name='readonly_projects', to=settings.AUTH_USER_MODEL)),
                ('readwrite_users', models.ManyToManyField(blank=True, related_name='readwrite_projects', to=settings.AUTH_USER_MODEL)),
                ('readwriteown_users', models.ManyToManyField(blank=True, related_name='readwriteown_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('classification', models.CharField(blank=True, max_length=50)),
                ('classification_type', models.CharField(choices=[('SP', 'Spectroscopic'), ('PH', 'Photometric')], default='PH', max_length=2)),
                ('observing_status', models.CharField(choices=[('FI', 'Finished'), ('ON', 'Ongoing'), ('RE', 'Rejected'), ('NE', 'New')], default='NE', max_length=2)),
                ('note', models.TextField(blank=True, default='')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=models.SET(users.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('description', models.TextField(default='')),
                ('color', models.CharField(default='#8B0000', max_length=7)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Project')),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stars', to='stars.Tag'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Project'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Star'),
        ),
    ]
