# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=50)),
                ('measurement', models.FloatField()),
                ('error', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('classification', models.CharField(max_length=50)),
                ('classification_type', models.CharField(choices=[('SP', 'Spectroscopic'), ('PH', 'Photometric')], default='PH', max_length=2)),
                ('observing_status', models.CharField(choices=[('FI', 'Finished'), ('ON', 'Ongoing'), ('RE', 'Rejected'), ('NE', 'New')], default='NE', max_length=2)),
                ('note', models.TextField(default='')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(default='')),
                ('color', models.CharField(default='#8B0000', max_length=7)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='tags',
            field=models.ManyToManyField(related_name='stars', to='stars.Tag'),
        ),
        migrations.AddField(
            model_name='photometry',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Star'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Star'),
        ),
    ]
