# Generated by Django 4.0.1 on 2022-04-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
