# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_auto_20170223_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
