# Generated by Django 4.1.2 on 2023-07-24 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stars', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identifier',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='project',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='star',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='star',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='star',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='project',
            name='full_starmap',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='preview_starmap',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(default='')),
                ('color', models.CharField(default='#8B0000', max_length=7)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stars.project')),
            ],
            options={
                'verbose_name': 'historical tag',
                'verbose_name_plural': 'historical tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStar',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('classification', models.CharField(blank=True, max_length=50)),
                ('classification_type', models.CharField(choices=[('SP', 'Spectroscopic'), ('PH', 'Photometric')], default='PH', max_length=2)),
                ('observing_status', models.CharField(choices=[('FI', 'Finished'), ('ON', 'Ongoing'), ('RE', 'Rejected'), ('NE', 'New')], default='NE', max_length=2)),
                ('note', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stars.project')),
            ],
            options={
                'verbose_name': 'historical star',
                'verbose_name_plural': 'historical stars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=20)),
                ('description', models.TextField(default='')),
                ('logo', models.TextField(blank=True, max_length=100, null=True)),
                ('preview_starmap', models.TextField(blank=True, max_length=100, null=True)),
                ('full_starmap', models.TextField(blank=True, max_length=100, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project',
                'verbose_name_plural': 'historical projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIdentifier',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('href', models.CharField(blank=True, max_length=400)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stars.project')),
                ('star', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stars.star')),
            ],
            options={
                'verbose_name': 'historical identifier',
                'verbose_name_plural': 'historical identifiers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
