# Generated by Django 4.2.30 on 2026-06-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0007_remove_project_starmap_png_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='starmap_cache_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='starmap_cache_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
