# Generated by Django 6.0.7 on 2026-07-22 07:48

import django.core.validators
import stars.models.project
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0008_project_starmap_cache_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=stars.models.project._project_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
