# Generated by Django 6.0.6 on 2026-07-14 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0026_multi_fit_rollout'),
        ('interop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteropSubFitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='astra', max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('fit_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameIndex(
            model_name='interoprecord',
            new_name='interop_int_source_10604f_idx',
            old_name='interop_rec_source__8f0f0d_idx',
        ),
        migrations.AddField(
            model_name='interopsubfitrecord',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interop_sub_fits', to='analysis.analysis'),
        ),
        migrations.AddField(
            model_name='interopsubfitrecord',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_fit_records', to='interop.interopimportbatch'),
        ),
        migrations.AddIndex(
            model_name='interopsubfitrecord',
            index=models.Index(fields=['source', 'external_id'], name='interop_int_source_9dc4f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='interopsubfitrecord',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='interop_subfit_unique_external'),
        ),
    ]
